[dev]
    command = 'pnpm start'
    publish = '_site'
    functions = 'netlify/functions'

[build]
  command = "pnpm build"
  publish = "_site"
  functions = 'netlify/functions'

[[redirects]]
  from = "*"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/404"
  to = "/404.html"
  status = 404
  force = true

[[redirects]]
  from = "/404/"
  to = "/404.html"
  status = 404
  force = true

[[plugins]]
  package = "netlify-plugin-cache"

  [plugins.inputs]
  paths = [ ".cache", "_webmentioncache" ]

[[plugins]]
  package = "@aciccarello/netlify-plugin-webmentions"

  [plugins.inputs]
  baseUrl = "https://www.ellyloel.com"
  feedPath = "feed.rss"
  limit = 80
