[dev]
    command = 'pnpm start'
    publish = '_site'
    functions = 'netlify/functions'

[build]
  command = "pnpm build"
  publish = "_site"
  functions = 'netlify/functions'

[[redirects]]
  from = "*"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/404"
  to = "/404.html"
  status = 404
  force = true

[[redirects]]
  from = "/404/"
  to = "/404.html"
  status = 404
  force = true

[[plugins]]
  package = "netlify-plugin-cache"

  [plugins.inputs]
  paths = [ ".cache", "_webmentioncache" ]

[[plugins]]
  package = "netlify-plugin-webmentions"

  [plugins.inputs]
  # Path to the feed URL (optional, default: /feed.xml)
  feedPath = "/feed.rss"

  # Maximum number of feed entries to check for mentions (optional, default: 1)
  limit = 10
