import "./shoelace.js";
import "./color-scheme.js";
import "./theme-hue.js";
import "./color-scheme-switcher-dialog.js";
import "./details-utils.js";
import "./css-doodle.js";
import "./howler.js";
import "./iframe.js";
import "./confetti.js";
