name: Scheduled build
on:
  schedule:
    - cron: '0 20 * * 0'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deploy hook on Cloudflare Pages
        env:
          TOKEN: ${​{ secrets.CLOUDFLARE_DEPLOY_HOOK }​}
        run: curl -X POST https://api.cloudflare.com/client/v4/pages/webhooks/deploy_hooks/${TOKEN}
